package com.cipolflo.server.clientes.exception;

public enum ClienteCodigoError {
    ID_INVALIDO,
    CLIENTE_NO_ENCONTRADO,
    SOCIO_NO_ENCONTRADO,
    CEDULA_INVALIDA,
    CEDULA_DUPLICADA,
    RUT_INVALIDO,
    RUT_DUPLICADO,
    EMAIL_INVALIDO,
    EMAIL_DUPLICADO,
    SOLICITUD_INVALIDA,
    PAGO_CUOTA_NO_ENCONTRADO,
    FECHA_INGRESO_INVALIDA,
    NUMERO_SOCIO_DUPLICADO,
    ARCHIVO_IMPORTACION_INVALIDO,
}