
# Base de datos - configurar cuando se cree la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/cipolflo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Nombre de la app
spring.application.name=cipolflo-server

# Puerto
server.port=8080