package com.cipolflo.server.shared.exception;

public enum ServicioCodigoError {
    SERVICIO_NO_ENCONTRADO,
    RESERVA_NO_CANCELABLE,
    CONFIRMACION_DEVOLUCION_REQUERIDA,
    PRECIO_SOCIO_MAYOR_O_IGUAL_PARTICULAR,
    NOMBRE_DUPLICADO,
    ID_INVALIDO,
    SOLICITUD_INVALIDA,
    RANGO_FECHAS_INVALIDO
}
