package com.cipolflo.server.shared.exception;

public enum ServicioCodigoError {
    SERVICIO_NO_ENCONTRADO,
    RESERVA_NO_CANCELABLE,
    CONFIRMACION_DEVOLUCION_REQUERIDA,
    NOMBRE_DUPLICADO,
    ID_INVALIDO,
    SOLICITUD_INVALIDA,
    RANGO_FECHAS_INVALIDO,
    TARIFA_NO_ENCONTRADA,
    RANGO_ANTIGUEDAD_INVALIDO,
    ANTIGUEDAD_NO_APLICABLE_A_PARTICULAR,
    TARIFA_SUPERPUESTA,
    TARIFAS_OBLIGATORIAS_FALTANTES,
    TARIFA_OBLIGATORIA_NO_ELIMINABLE,
    TARIFA_NO_ENCONTRADA_PARA_CLIENTE
}
