package com.cipolflo.server.reservas.exception;

public enum ReservaCodigoError {
    RESERVA_NO_ENCONTRADA,
    FECHAS_SOLAPADAS,
    CLIENTE_REQUERIDO,
    NOMBRE_REQUERIDO_PARA_CREAR_CLIENTE,
    CEDULA_REQUERIDA_PARA_CREAR_CLIENTE,
    CELULAR_REQUERIDO_PARA_CREAR_CLIENTE,
    FECHA_FIN_ANTERIOR_A_INICIO,
    FECHA_PASADA,
    SERVICIO_NO_DISPONIBLE,
    RUT_SOLO_VALIDO_EN_COLABORACION,
    RESERVA_NO_MODIFICABLE
    HORA_REQUERIDA_PARA_SERVICIO_POR_HORA,
    HORA_NO_PERMITIDA_PARA_MODALIDAD,
    HORA_FIN_ANTERIOR_O_IGUAL_A_INICIO
}
